[tool.poetry]
name = "windows-12-v2"
version = "0.1.0"
description = ""
authors = ["Your Name <Tylerwdiscord@gmail.com"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
